# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 658)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setEnabled(True)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setDocumentTitle(_translate("Dialog", "Инструкция по \"\n"
"                      \"применению."))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Инструкция по \"\n"
"                      \"применению.</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Это попытка изобрести велосипед. Я попытался сделать удобный инженерный калькулятор, на котором удобно считать тригонометрические функции, логарифмы, извлечения корня, возведения в степень, расчёт площади различных фигур и другие вычисления использующие различные константы. Так-же можно производить другие вычисления используя выражения со скобками. Все полученные результаты отображаются в правой половине верхнего окна. Результат можно быстро вернуть в строку ввода, нужно просто кликнуть по нужному.Обратное число вычисляется вводом исходного числа и нажатием кнопки &quot;1/х&quot;.Проценты вычисляются вводом исходного числа, вводом знака + или - , вводом процентов и нажатием кнопки &quot;%&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Что такое логарифм?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Логарифм по основанию a от аргумента x , это степень в которую надо возвести число a, чтобы плучить число x.Обозначение: </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">log</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">ₐ</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">x = b</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">, где a — основание, x — аргумент, b — собственно, чему равен логарифм.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Логарифм по основанию 10 обозначается как </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">lg x</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">, т.е </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">lg x</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\"> = </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">log₁₀ x</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Натуральный логарифм от аргумента x — это логарифм по основанию </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">e</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">, т.е. степень, в которую надо возвести число e, чтобы получить число x. Обозначение: </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">ln x</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Многие спросят: что еще за число </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">e</span><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">? Это иррациональное число, его точное значение найти и записать невозможно. Приведу лишь первые его цифры:<br /></span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\">e = 2,718281828459...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Не будем углубляться, что это за число и зачем нужно. Просто помните, что e — основание натурального логарифма: </span><span style=\" font-family:\'Noto Sans\'; font-size:14pt; font-style:italic;\"> ln x = logₑx</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Noto Sans\'; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Теперь о вводе с клавиатуры.Ввод производится на латинице, это сделано для удобства, т.к тригонометрические функции написаны на латинице и это облегчает использование мнемоник.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Мнемоники это подчёркнутые символы в названии кнопок. Например что-бы ввести cos нужно нажать &quot;Alt +  &quot;c&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Чтобы увидеть все мнемоники просто нажмите клавишу&quot;Alt&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Цифры вводятся простым нажатием соответствующей клавиши. Символы &quot;+&quot;  &quot;-&quot;  &quot;=&quot;  &quot;%&quot;  также вводятся нажатием соответствующей клавиши.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Для вычисления обратного числа нужно нажать клавишу &quot;x&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Для очистки всех полей, клавиша &quot;c&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Для перемещения курсора используются клавиши со стрелками. Для удаления символов используется клавиша &quot;backspace&quot;. Для ввода знака умножения клавиша &quot;*&quot;, а для деления клавиша &quot;/&quot;.Для ввода подстрочных цифр используется комбинация клавиш &quot;Ctrl&quot; +  &quot;цифровая клавиша&quot;.<br /></span></p></body></html>"))
