# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 658)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setEnabled(True)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setDocumentTitle(_translate("Dialog", "Инструкция по \"\n"
                                                  "\"применению."))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><title>Инструкция по \"\n"
"                      \"применению.</title><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Это попытка изобрести велосипед. Я попытался сделать удобный инженерный &quot; &quot;калькулятор, на котором удобно считать тригонометрические функции, логарифмы, извлечения &quot; &quot;корня, возведения в степень, расчёт площади различных фигур и другие вычисления использующие &quot; &quot;различные константы. Так-же можно производить другие вычисления используя выражения со &quot; &quot;скобками. Все полученные &quot; &quot;результаты отображаются в правой половине верхнего окна. Результат можно быстро вернуть в &quot; &quot;строку ввода, нужно просто кликнуть по нужному.Обратное число &quot; &quot;вычисляется вводом исходного числа и нажатием кнопки 1/х.Проценты вычисляются &quot; &quot;вводом исходного числа, вводом знака + или - , вводом процентов и нажатием кнопки &quot; &quot;%.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Что &quot; &quot;такое логарифм?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Логарифм по основанию a от аргумента x , &quot; &quot;это степень,,в которую надо возвести число a, чтобы плучить число x.Обозначение: &quot; &quot;logax = b, где a — основание, x — аргумент, b — собственно, чему равен &quot; &quot;логарифм.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Логарифм по основанию 10 &quot; &quot;обозначается как lg x, т.е lg x = &quot; &quot;log10 x.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Натуральный &quot; &quot;логарифм &quot; &quot;от аргумента x — это логарифм по основанию e, т.е. степень, в которую надо возвести число e, чтобы получить число x. Обозначение: ln x. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Многие &quot; &quot;спросят: что еще за число e? Это &quot; &quot;иррациональное число, его точное значение найти и записать невозможно. Приведу лишь первые его &quot; &quot;цифры:<br />e = 2,718281828459...</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Не будем углубляться, что это за число и зачем нужно. Просто помните, &quot; &quot;что e — &quot; &quot;основание натурального логарифма:  x = &quot; &quot;loge x</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Теперь о вводе с клавиатуры.Ввод &quot; &quot;производится на латинице, это сделано для удобства, т.к тригонометрические функции написаны на &quot; &quot;латинице и это облегчает использование мнемоник.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Мнемоники это &quot; &quot;подчёркнутые символы в названии кнопок. Например что-бы ввести cos нужно нажать &quot;Alt + &quot; &quot;c&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Чтобы увидеть все мнемоники &quot; &quot;просто нажмите клавишу&quot;Alt&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Цифры вводятся &quot; &quot;простым нажатием соответствующей клавиши. Символы &quot;+&quot; &quot;-&quot; &quot;=&quot; &quot; &quot;&quot;%&quot; также вводятся нажатием соответствующей клавиши.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Для вычисления обратного числа нужно нажать клавишу &quot; &quot;&quot;x&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Для очистки всех полей, &quot; &quot;клавиша &quot;c&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Для перемещения курсора &quot; &quot;используются клавиши со стрелками. Для удаления символов используется клавиша &quot; &quot;&quot;backspace&quot;. Для ввода знака умножения клавиша &quot;*&quot;, а для деления клавиша &quot; &quot;&quot;/&quot;.Для ввода подстрочных цифр используется комбинация клавиш &quot;Ctrl&quot; + &quot; &quot;&quot;цифровая клавиша&quot;.<br /></span></p></body></html>"))
