# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, DialogHelp):
        DialogHelp.setObjectName("DialogHelp")
        DialogHelp.resize(700, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(DialogHelp)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(DialogHelp)
        self.textEdit.setEnabled(True)
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setUndoRedoEnabled(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)

        self.retranslateUi(DialogHelp)
        QtCore.QMetaObject.connectSlotsByName(DialogHelp)

    def retranslateUi(self, DialogHelp):
        _translate = QtCore.QCoreApplication.translate
        DialogHelp.setWindowTitle(_translate("DialogHelp", "Dialog"))
        self.textEdit.setDocumentTitle(_translate("DialogHelp", "Инструкция по применению."))
        self.textEdit.setHtml(_translate("DialogHelp", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" "
                                                       "\"http://www.w3.org/TR/REC-html40/strict.dtd\">\n "
                                                       "<html><head><meta name=\"qrichtext\" content=\"1\" "
                                                       "/><title>Инструкция по применению.</title><style "
                                                       "type=\"text/css\">\n "
                                                       "p, li { white-space: pre-wrap; }\n"
                                                       "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; "
                                                       "font-size:8.25pt; font-weight:400; "
                                                       "font-style:normal;\">\n "
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; "
                                                       "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                                       "text-indent:0px;\"><span style=\" font-size:14pt;\">Это "
                                                       "попытка изобрести велосипед. Я попытался сделать удобный "
                                                       "инженерный калькулятор, на котором удобно считать "
                                                       "тригонометрические функции, логарифмы, извлечения корня, "
                                                       "возведения в степень, расчёт площади различных фигур и другие "
                                                       "вычисления использующие различные константы. Так-же можно "
                                                       "производить другие вычисления используя выражения со "
                                                       "скобками. </span></p>\n "
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; "
                                                       "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                                       "text-indent:0px;\"><span style=\" font-size:14pt;\">Все "
                                                       "полученные результаты отображаются в правой половине верхнего "
                                                       "окна. Результат можно быстро вернуть в строку ввода, "
                                                       "нужно просто кликнуть по нужному.</span></p>\n "
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; "
                                                       "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                                       "text-indent:0px;\"><span style=\" font-size:14pt;\">Обратное "
                                                       "число вычисляется вводом исходного числа и нажатием кнопки "
                                                       "1/х.</span></p>\n "
                                                       "<p style=\" margin-top:0px; margin-bottom:0px; "
                                                       "margin-left:0px; margin-right:0px; -qt-block-indent:0; "
                                                       "text-indent:0px;\"><span style=\" font-size:14pt;\">Проценты "
                                                       "вычисляются вводом исходного числа, вводом знака + или - ,  "
                                                       "вводом процентов и нажатием кнопки "
                                                       "%.</span></p></body></html>"))
